jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Orbital Transfer
        run: |
          sudo apt-get install ikiwiki libtext-multimarkdown-perl
